name: Sync Google Sheets

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      CREDENTIALS_B64: ${{ secrets.CREDENTIALS_B64 }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client pandas

      - name: Run sync script
        run: python sync_script.py
