name: Sync Google Sheets

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.CREDENTIALS_JSON }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install gspread oauth2client pandas

      - name: Run sync script
        run: python sync_script.py
